apiVersion: v1
kind: Service
metadata:
  name: basic-greetings
  labels:
    app: basic-greetings
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: basic-greetings
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: basic-greetings
spec:
  replicas: {{ .Values.basic-greetings.instances }}
  selector:
    matchLabels:
      app: basic-greetings
  template:
    metadata:
      labels:
        app: basic-greetings
    spec:
      containers:
      - name: basic-greetings
        image: harbor.tan.springapps.io/basic-greetings:pks-demo-concourse
        imagePullPolicy: Always
        containerPort: 8080
