resource_types:
- name: helm
  type: docker-image
  source:
    repository: nierajsingh/concourse-helm-resource
resources:
- name: git
  type: git
  source:
    uri: git@github.com:nierajsingh/chatter.git
    private_key: {{rsa_id}}
    branch: k8s
- name: jdk
  type: docker-image
  source:
    repository: openjdk
    tag: 8-jdk
- name: {{app_docker_image_name}}
  type: docker-image
  source:
    repository: {{harbor_app_image_repository}}
    tag: pks-demo-concourse
    username: {{harbor_username}}
    password: {{harbor_password}}
    ca_certs:
    - domain: harbor.tan.springapps.io:4443
      cert: {{harbor_ca_cert}}
    insecure_registries:
    - harbor.tan.springapps.io
- name: pks-demo-helm
  type: helm
  source:
    kube_config: {{kube_config}}
    release: pks-demo-app
jobs:
- name: build-pks-demo-app
  plan:
  - aggregate:
    - get: git
      trigger: true
    - get: jdk
  - task: build
    file: git/ci/tasks/build-fat-jar.yml
    params:
      app_name: {{app_name}}
    image: jdk
  - put: {{app_docker_image_name}}
    params:
      build: out
    get_params:
      skip_download: true
- name: {{app_deployment_name}}
  plan:
  - aggregate:
    - get: git
    - get: {{app_docker_image_name}}
      passed:
      - build-pks-demo-app
      trigger: true
      params:
        skip_download: true       
  - put: pks-demo-helm
    params:
      chart: {{app_helm_chart}}
      recreate_pods: true
